<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Config' => $baseDir . '/model/Config.class.php',
    'Config_Cart' => $baseDir . '/model/Cart.class.php',
    'Config_Checkout' => $baseDir . '/model/Checkout.class.php',
    'Config_Contact' => $baseDir . '/model/Contact.class.php',
    'Config_Login' => $baseDir . '/model/Register.class.php',
    'Config_Prod' => $baseDir . '/model/Produtos.class.php',
    'Config_Prod_D' => $baseDir . '/model/Product_D.class.php',
    'EasyPeasyICS' => $vendorDir . '/phpmailer/phpmailer/extras/EasyPeasyICS.php',
    'PHPMailer' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
    'PHPMailerOAuth' => $vendorDir . '/phpmailer/phpmailer/class.phpmaileroauth.php',
    'PHPMailerOAuthGoogle' => $vendorDir . '/phpmailer/phpmailer/class.phpmaileroauthgoogle.php',
    'POP3' => $vendorDir . '/phpmailer/phpmailer/class.pop3.php',
    'Rotas' => $baseDir . '/model/Rotas.class.php',
    'SMTP' => $vendorDir . '/phpmailer/phpmailer/class.smtp.php',
    'Template' => $baseDir . '/model/Template.class.php',
    'ntlm_sasl_client_class' => $vendorDir . '/phpmailer/phpmailer/extras/ntlm_sasl_client.php',
    'phpmailerException' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
);
