<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit844f9577838b0f54d4f2e348e6b23fb8
{
    public static $files = array (
        'f084d01b0a599f67676cffef638aa95b' => __DIR__ . '/..' . '/smarty/smarty/libs/bootstrap.php',
    );

    public static $classMap = array (
        'Config' => __DIR__ . '/../..' . '/model/Config.class.php',
        'Config_Cart' => __DIR__ . '/../..' . '/model/Cart.class.php',
        'Config_Checkout' => __DIR__ . '/../..' . '/model/Checkout.class.php',
        'Config_Contact' => __DIR__ . '/../..' . '/model/Contact.class.php',
        'Config_Login' => __DIR__ . '/../..' . '/model/Register.class.php',
        'Config_Prod' => __DIR__ . '/../..' . '/model/Produtos.class.php',
        'Config_Prod_D' => __DIR__ . '/../..' . '/model/Product_D.class.php',
        'EasyPeasyICS' => __DIR__ . '/..' . '/phpmailer/phpmailer/extras/EasyPeasyICS.php',
        'PHPMailer' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmailer.php',
        'PHPMailerOAuth' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmaileroauth.php',
        'PHPMailerOAuthGoogle' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmaileroauthgoogle.php',
        'POP3' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.pop3.php',
        'Rotas' => __DIR__ . '/../..' . '/model/Rotas.class.php',
        'SMTP' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.smtp.php',
        'Template' => __DIR__ . '/../..' . '/model/Template.class.php',
        'ntlm_sasl_client_class' => __DIR__ . '/..' . '/phpmailer/phpmailer/extras/ntlm_sasl_client.php',
        'phpmailerException' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmailer.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit844f9577838b0f54d4f2e348e6b23fb8::$classMap;

        }, null, ClassLoader::class);
    }
}
